
MY_CHOICES = (
              ('Allergist or Immunologist ', 'Allergist or Immunologist '),
              ('Anesthesiologist', 'Anesthesiologist'),
              ('Cardiologist', 'Cardiologist'),
              ('Dermatologist ', 'Dermatologist '),
              ('Gastroenterologist ', 'Gastroenterologist '),
              
              ('Hematologist/Oncologist ', 'Hematologist/Oncologist '),
              ('Internal Medicine Physician', 'Internal Medicine Physician'),
              ('Nephrologist  ', 'Nephrologist  '),
              ('Neurologist  ', 'Neurologist  '),

              ('Neurosurgeon', 'Neurosurgeon'),
              ('Obstetrician ', 'Obstetrician '),
              ('Gynecologist ', 'Gynecologist '),
              ('Nurse-Midwifery ', 'Nurse-Midwifery '),

              ('Physician', 'Physician'),
              ('Ophthalmologist ', 'Ophthalmologist '),
              ('Oral and Maxillofacial Surgeon ', 'Oral and Maxillofacial Surgeon '),
              ('Orthopaedic Surgeon ', 'Orthopaedic Surgeon '),

              ('Otolaryngologist ', 'Otolaryngologist '),
              ('Pathologist ', 'Pathologist  '),
              ('Pediatrician ', 'Pediatrician '),
              ('Plastic Surgeon ', 'Plastic Surgeon  '),


              ('Podiatrist ', 'Podiatrist '),
              ('Psychiatrist ', 'Psychiatrist '),
              ('Pulmonary Medicine Physician ', 'Pulmonary Medicine Physician'),
              ('Radiation Onconlogist  ', 'Radiation Onconlogist '),

              ('Diagnostic Radiologist ', 'Diagnostic Radiologist '),
              ('Diagnostic Radiologist ', 'Diagnostic Radiologist '),
              ('Diagnostic Radiologist ', 'Diagnostic Radiologist ')
            )



statee = {
    'Allergist or Immunologist': 'Allergist or Immunologist ',
    'Anesthesiologist': 'Anesthesiologist',
    'Cardiologist': 'Cardiologist',
    'Dermatologist ': 'Dermatologist ',
    'Gastroenterologist': 'Gastroenterologist',
    'Hematologist/Oncologist': 'Hematologist/Oncologist ',
    'Internal Medicine Physician': 'Internal Medicine Physician',
    'Nephrologist  ': 'Nephrologist  ',
    'Neurologist  ': 'Neurologist  ',
    'Neurosurgeon': 'Neurosurgeon',
    'Obstetrician ': 'Obstetrician ',
    'Gynecologist ': 'Gynecologist ',
    'Nurse-Midwifery ': 'Nurse-Midwifery ',
    'Physician': 'Physician',
    'Ophthalmologist ': 'Ophthalmologist ',
    'Oral and Maxillofacial Surgeon ': 'Oral and Maxillofacial Surgeon ',
    'Orthopaedic Surgeon ': 'Orthopaedic Surgeon ',
    'Otolaryngologist ': 'Otolaryngologist ',
    'Pathologist ': 'Pathologist  ',
    'Pediatrician ': 'Pediatrician ',
    'Plastic Surgeon ': 'Plastic Surgeon  ',
    'Podiatrist ': 'Podiatrist ',
    'Psychiatrist ': 'Psychiatrist ',
    'Pulmonary Medicine Physician ': 'Pulmonary Medicine Physician',
    'Radiation Onconlogist  ': 'Radiation Onconlogist ',
    'Diagnostic Radiologist  ': 'Diagnostic Radiologist ',
    'Diagnostic Radiologist ': 'Diagnostic Radiologist ',
    'Diagnostic Radiologist   ': 'Diagnostic Radiologist '
}



state_choices = {
        'Warsaw':'Warsaw',
        'Kraków':'Kraków',
        'Wrocław':'Wrocław',
        'Poznań':'Poznań',
        'Gdańsk':'Gdańsk',
        'Szczecin': 'Szczecin',
        'Bydgoszcz':'Bydgoszcz',
        'Lublin':'Lublin',
        'Gdynia':'Gdynia',
        'Radom': 'Radom',
        'Katowice':'Katowice',
        'Kielce':'Kielce',
        'Zakopane':'Zakopane',
        'New Delhi':'New Delhi',
        'Mumbai':'Mumbai',
        'Kolkata':'Kolkata',
        'Banglore':'Banglore',
        'Bihar':'Bihar',
        'Uttar Pradesh':'Uttar Pradesh',
        'HR':'Haryana',
        'Haryana':'Jammu Kashmir',
        'Himachel Pradesh':'Himachel Pradesh',
        'UttraKhand':'UttraKhand',
        'Kerla':'Kerla',
        'Chenni':'Chenni',
        'Gujrat':'Gujrat',
        'Rajasthan':'Rajasthan',
        'Andhra Pradesh':'Andhra Pradesh',
        'Assam':'Assam',
        'Arunachal Pradesh ':'Arunachal Pradesh ',
        'Chhattisgarh':'Chhattisgarh',
        'Goa':'Goa',
        'Jharkhand':'Jharkhand',
        'Karnataka':'Karnataka',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}
