# Generated by Django 2.0.4 on 2019-03-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='photourl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
