# Generated by Django 2.0.4 on 2019-03-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_photourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospitallink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
