# Generated by Django 2.0.4 on 2019-03-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20190317_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='type',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Clinic', 'Clinic')], default='public', max_length=100),
        ),
    ]
