# Generated by Django 2.0.4 on 2019-03-17 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hospital_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='regadate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
