# Generated by Django 2.0.4 on 2019-04-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_hospital_regadate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='photo',
            field=models.ImageField(default='noimage.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
