# Generated by Django 2.0.4 on 2019-03-16 19:28

import datetime
from django.db import migrations, models
import multiselectfield.db.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('specialization', multiselectfield.db.fields.MultiSelectField(choices=[('Allergist or Immunologist ', 'Allergist or Immunologist '), ('Anesthesiologist', 'Anesthesiologist'), ('Cardiologist', 'Cardiologist'), ('Dermatologist ', 'Dermatologist '), ('Gastroenterologist ', 'Gastroenterologist '), ('Hematologist/Oncologist ', 'Hematologist/Oncologist '), ('Internal Medicine Physician', 'Internal Medicine Physician'), ('Nephrologist  ', 'Nephrologist  '), ('Neurologist  ', 'Neurologist  '), ('Neurosurgeon', 'Neurosurgeon'), ('Obstetrician ', 'Obstetrician '), ('Gynecologist ', 'Gynecologist '), ('Nurse-Midwifery ', 'Nurse-Midwifery '), ('Physician', 'Physician'), ('Ophthalmologist ', 'Ophthalmologist '), ('Oral and Maxillofacial Surgeon ', 'Oral and Maxillofacial Surgeon '), ('Orthopaedic Surgeon ', 'Orthopaedic Surgeon '), ('Otolaryngologist ', 'Otolaryngologist '), ('Pathologist ', 'Pathologist  '), ('Pediatrician ', 'Pediatrician '), ('Plastic Surgeon ', 'Plastic Surgeon  '), ('Podiatrist ', 'Podiatrist '), ('Psychiatrist ', 'Psychiatrist '), ('Pulmonary Medicine Physician ', 'Pulmonary Medicine Physician'), ('Radiation Onconlogist  ', 'Radiation Onconlogist '), ('Diagnostic Radiologist  ', 'Diagnostic Radiologist '), ('Diagnostic Radiologist ', 'Diagnostic Radiologist '), ('Diagnostic Radiologist   ', 'Diagnostic Radiologist ')], max_length=528)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('about', tinymce.models.HTMLField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=150)),
                ('hospitallink', models.CharField(max_length=150)),
                ('portfoliolink', models.CharField(max_length=150)),
                ('timing', tinymce.models.HTMLField()),
                ('experiance', models.IntegerField()),
                ('regadate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
