# Generated by Django 2.0.4 on 2019-03-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20190316_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Allergist or Immunologist ', 'Allergist or Immunologist '), ('Anesthesiologist', 'Anesthesiologist'), ('Cardiologist', 'Cardiologist'), ('Dermatologist ', 'Dermatologist '), ('Gastroenterologist ', 'Gastroenterologist '), ('Hematologist/Oncologist ', 'Hematologist/Oncologist '), ('Internal Medicine Physician', 'Internal Medicine Physician'), ('Nephrologist  ', 'Nephrologist  '), ('Neurologist  ', 'Neurologist  '), ('Neurosurgeon', 'Neurosurgeon'), ('Obstetrician ', 'Obstetrician '), ('Gynecologist ', 'Gynecologist '), ('Nurse-Midwifery ', 'Nurse-Midwifery '), ('Physician', 'Physician'), ('Ophthalmologist ', 'Ophthalmologist '), ('Oral and Maxillofacial Surgeon ', 'Oral and Maxillofacial Surgeon '), ('Orthopaedic Surgeon ', 'Orthopaedic Surgeon '), ('Otolaryngologist ', 'Otolaryngologist '), ('Pathologist ', 'Pathologist  '), ('Pediatrician ', 'Pediatrician '), ('Plastic Surgeon ', 'Plastic Surgeon  '), ('Podiatrist ', 'Podiatrist '), ('Psychiatrist ', 'Psychiatrist '), ('Pulmonary Medicine Physician ', 'Pulmonary Medicine Physician'), ('Radiation Onconlogist  ', 'Radiation Onconlogist '), ('Diagnostic Radiologist  ', 'Diagnostic Radiologist '), ('Diagnostic Radiologist ', 'Diagnostic Radiologist '), ('Diagnostic Radiologist   ', 'Diagnostic Radiologist ')], default='Cardiologist', max_length=100),
        ),
    ]
