# Generated by Django 2.0.4 on 2019-03-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20190316_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Country', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
