# Generated by Django 2.0.4 on 2019-03-16 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_emergency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergency',
            old_name='Country',
            new_name='country',
        ),
    ]
