# Generated by Django 2.0.4 on 2019-03-17 15:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20190316_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', tinymce.models.HTMLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Specialist',
        ),
    ]
