# Generated by Django 2.0.4 on 2019-03-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_auto_20190317_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availabel',
            field=models.CharField(default='MON-FRI: 9:00 - 18:00 ', max_length=200),
        ),
    ]
