# Generated by Django 2.0.4 on 2019-04-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_auto_20190317_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_newsletter', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='documents',
            field=models.FileField(default='img.pdf', upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
